# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ShareUIDemo' do

#pod 'ShareUI', '~> 0.0.1'


end

target 'ShareUIDemoTests' do

end

target 'ShareUIDemoUITests' do

end

